### ISSUE TITLE
It does not work in kali linux 

### ISSUE THREAD

**Issue by reyanRaj** [molikuner/android-development-32bit#8]
It is showing unable to find build tools.
Any other way.

**Comment by molikuner** [comment]
Hey, I don't think this is still working. As I noted in #7 the executable will be replaced by the build tools, if it detects an "invalid" version via a different md5 hash. This will be the issue you will probably run into once you got it setup correctly.
But to be honest, I don't think there is any need to run 32-bit Linux today as a development machine. Even my 15 years old PC can run 64 bit already and it is way to slow to be productive while compiling.
Apart from that:

Are you really on a 32 bit installation of kali linux? Could you show the output of `uname -a`?
Also what error do you get, if you don't do anything from this guide? If this isn't working either, you will need to setup [Android Studio](https://developer.android.com/studio/#downloads) correctly.

**Comment by reyanRaj** [comment]
I have 32 bit cpu with 32 bit Operating system with 2 gigs of ram . Can i
able to run Android studio on linux. In windows it is quite slow.

**Comment by molikuner** [comment]
Well, is it possible? Yes, definitely. Swap is a thing, so your machine could use that instead, if the ram is full.
Is it a nice experience? Most probably not. Swap is SLOW and so is everything that uses the data from it. At work they just doubled my ram because my colleagues said, that my machine is too slow. So if there is any possibility to use an machine with better specs, you should!

I can't really help you to setup build tools. Depending on what you want to do, it might be sufficient to install the CLI tools from [here](https://developer.android.com/studio/#downloads). This should enable you to compile apps after installing the build tools via the `sdkmanager` like [here](https://developer.android.com/studio/command-line/sdkmanager#install_packages).

After that you should try to build an app by pointing to your build-tools installation, but it will fail because of 32-bit support. If you are this far, then you can try to follow this guide. But still, this guide isn't complete anymore. The binary will be replaced once a change to it is detected via an MD5 hash. You would need to solve #7 yourself, since I don't do android development privately right now and I don't use any Linux 32-bit anymore.

**Comment by reyanRaj** [comment]
Any alternative of android studio for building android app in kotlin.

**Comment by molikuner** [comment]
Not that I know of. Of course you can use IntelliJ IDEA, but it's only marginally faster in my experience and not so well tailored to android, which means almost no android specific support like view-previews.
Do you want to write code, or just compile it on that machine? Compiling should be possible with some effort (probably still not worth it), but writing in an IDE? Well that's kind of a stretch nowadays with that kind of hardware.

**Comment by reyanRaj** [comment]
Can you tell me about fiverr
And How to get first client?

**Comment by reyanRaj** [comment]
Can you tell me about fiverr. How to get first client.

**Comment by reyanRaj** [comment]
Can I run android studio on google collab. Or etablish rdp on collab
Or any other free cloud platform.

**Comment by molikuner** [comment]
Sorry, I do not have any experience with such services. This also seems to be off topic. Closing the issue now.
